blog/urls.py
from django.urls import path, include

from . import views

from .feeds import BlogPostFeed

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/<slug:slug>/", views.PostView.as_view(), name="post"),
    path("tag/<int:pk>/", views.TagDetailView.as_view(), name="tag"),
    path("rss/", BlogPostFeed(), name="rss")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    #path("gallery/", include("gallery.urls", namespace="gallery")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path, include

from . import views

app_name = "portfolio"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("cv/", views.CVView.as_view(), name="cv"),
    path("<slug:slug>/", views.ProjectDetailView.as_view(), name="project_detail"),
]

portfolio/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=100, blank=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    version_control = models.URLField(null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    description = models.CharField(max_length=200, blank=True)
    text = models.TextField(max_length=2000, blank=True)
    featured = models.BooleanField(default=False)
    category = models.ManyToManyField(Category, blank=True, related_name="projects")
    created_date = models.DateTimeField(auto_now_add=timezone.now)
    updated_date = models.DateTimeField(auto_now=timezone.now)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse("portfolio:project_detail", args=[self.slug])


class School(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(blank=True, upload_to="images/portfolio/education")
    website = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class WorkPlace(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(blank=True, upload_to="images/portfolio/work")
    website = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Education(models.Model):
    school = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        null=True,
        blank=False
    )
    start_date = models.DateField()
    end_date = models.DateField()
    grade = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.school.name


class Work(models.Model):
    work_place = models.ForeignKey(
        WorkPlace,
        on_delete=models.CASCADE,
        null=True,
        blank=False
    )
    job_title = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    text = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.work_place.name


class Achievement(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    date_of_award = models.DateField()

    def __str__(self):
        return self.name

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView

from .models import Project, Education, Work, Achievement

class IndexView(ListView):
    template_name = "portfolio/index.html"
    model = Project

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["featured_list"] = Project.objects.filter(featured=True)

        return data


class ProjectDetailView(DetailView):
    template_name = "portfolio/detail.html"
    model = Project


class CVView(TemplateView):
    template_name = "portfolio/cv.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["education_list"] = Education.objects.order_by("-start_date")
        data["work_list"] = Work.objects.order_by("-start_date")
        data["achievement_list"] = Achievement.objects.order_by("-date_of_award")

        return data

portfolio/templates/portfolio/base.html
{% extends "core/core.html" %}

{% block content %}

{% include "core/navbar.html" %}

<section class="">
    {% block portfolio_content %}
    {% endblock portfolio_content %}
</section>

{% include "core/footer.html" %}

{% endblock content %}

portfolio/templates/portfolio/cv.html
{% extends "portfolio/base.html" %}

{% block portfolio_content %}

{% load static %}

<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            CV
        </h1>
    </div>
</header>
<main>
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">

        <div class="flex flex-col gap-5">

            {% if education_list %}
            <div class="flex flex-col gap-y-5">
                <h1 class="font-bold text-2xl">
                    Education
                </h1>
                {% for education in education_list %}
                <div class="flex border-l-4 pl-2">

                    <div>
                        <img src="{{education.school.image.url}}" width="50" class="border border-gray-200 rounded-sm mr-2" />
                    </div>

                    <div class="flex-1">
                        {% if education.school.website %}
                        <a href="{{education.school.website}}" target="_blank" class="underline text-blue-400">
                            {{education.school.name}}
                        </a>
                        {% else %}
                        <h1 class="">
                            {{education.school.name}}
                        </h1>
                        {% endif %}
                        <p class="font-bold text-sm">
                            {{education.grade}}
                        </p>
                        <p class="text-sm text-gray-700">
                            {{education.start_date|date:"M Y"}} - {{education.end_date|date:"M Y"}}
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            {% if work_list %}
            <div class="flex flex-col gap-y-5">
                <h1 class="font-bold text-2xl">
                    Experience
                </h1>

                {% for work in work_list %}
                <div class="flex border-l-4 pl-2">

                    <div>
                        {% if work.work_place.image %}
                        <img src="{{work.work_place.image.url}}" class="border border-gray-200 rounded-sm mr-2 w-12" />
                        {% else %}
                        <img src="{% static 'portfolio/images/experience_default.png' %}" width="50" class="border border-gray-200 rounded-sm mr-2" />
                        {% endif %}
                    </div>

                    <div class="flex-1">
                        <h1 class="">
                            {{work.job_title}}
                        </h1>

                        {% if work.work_place.website %}
                        <a href="{{work.work_place.website}}" target="_blank" class="underline text-blue-400">
                            {{work.work_place.name}}
                        </a>
                        {% else %}
                        <a class="">
                            {{work.work_place.name}}
                        </a>
                        {% endif %}

                        <p class="text-sm mb-2">
                            {{work.text}}
                        </p>
                        <p class="text-sm text-gray-700">
                            {{work.start_date|date:"M Y"}} - {{work.end_date|date:"M Y"}}
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

            {% if achievement_list %}
            <div class="flex flex-col gap-y-5">
                <h1 class="font-bold text-2xl">
                    Achievements
                </h1>

                {% for achievement in achievement_list %}
                <div class="flex border-l-4 pl-2">

                    <div class="">
                        <h1 class="font-bold">
                            {{achievement.name}}
                        </h1>

                        <p class="text-sm mb-2">
                            {{achievement.description}}
                        </p>
                        <p class="text-sm text-gray-700">
                            {{achievement.date_of_award|date:"M Y"}}
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

    </div>
</main>


{% endblock portfolio_content %}

portfolio/templates/portfolio/detail.html
{% extends "portfolio/base.html" %}

{% block portfolio_content %}

<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            {{project.name}}
        </h1>
    </div>
</header>
<main>
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="flex flex-col gap-5">
            {% if project.version_control %}
            <a href="{{project.version_control}}" class="underline text-blue-500">
                GitHub
            </a>
            {% endif %}

            {% if project.website %}
            <a href="{{project.website}}" class="underline text-blue-500">
                Website
            </a>
            {% endif %}

        </div>

    </div>
</main>

{% endblock portfolio_content %}

portfolio/templates/portfolio/index.html
{% extends "portfolio/base.html" %}

{% block portfolio_content %}

<header class="bg-gray-50 text-black">
  <div class="mx-auto max-w-7xl px-4 py-16">
    <h1 class="text-5xl font-bold mb-5">
      Portfolio
    </h1>
    <p class="">
      My projects and various work can be see listed here on this page.
    </p>
  </div>
</header>
<main>
  <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">

    <div class="">
      <h1 class="font-bold text-2xl py-4">
        Featured Work
      </h1>

      <div class="grid grid-cols-3 gap-4">
        {% for project in featured_list %}
        <div class="border rounded px-5 py-4 shadow">
          <a href="{{project.get_absolute_url}}" class="text-blue-500 text-2xl font-bold underline">
            {{project.name}}
          </a>
          <p>
            {{project.description}}
          </p>
          <div class="text-sm bg-blue-200">
            {% for category in project.category.all %}
            <a href="#">
              {{category.name}}
            </a>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    <hr class="border border-black my-5">

    <div>
      <h1 class="font-bold text-2xl py-4">
        All Projects
      </h1>


      <div class="grid grid-cols-3 gap-4">
        {% for project in project_list %}
        <div class="border rounded px-5 py-4">
          <a href="{{project.get_absolute_url}}" class="text-blue-500 text-2xl font-bold underline">
            {{project.name}}
          </a>
          <p>
            {{project.description}}
          </p>
          <span class="text-sm">
            {% for category in project.category.all %}
            {{category.name}}
            {% endfor %}
          </span>
        </div>
        {% endfor %}
      </div>
    </div>

  </div>
</main>

{% endblock portfolio_content %}