blog/urls.py
from django.urls import path, include

from . import views

from .feeds import BlogPostFeed

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/<slug:slug>/", views.PostView.as_view(), name="post"),
    path("tag/<int:pk>/", views.TagDetailView.as_view(), name="tag"),
    path("rss/", BlogPostFeed(), name="rss")
]

gallery/urls.py
from django.urls import path, include

from . import views

app_name = "gallery"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("albums/", views.AlbumView.as_view(), name="albums"),
    path("albums/<int:pk>", views.AlbumDetailView.as_view(), name="album_detail")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    #path("gallery/", include("gallery.urls", namespace="gallery")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Album(models.Model):
    name = models.CharField(max_length=100)
    cover = models.ImageField(blank=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("gallery:album_detail", args=[self.id])


class Image(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    upload_date = models.DateTimeField(auto_now_add=timezone.now)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True, blank=True)

gallery/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from .models import Album, Image

class IndexView(ListView):
    template_name = "gallery/index.html"
    paginate_by = 20

    def get_queryset(self):
        return Image.objects.order_by("-upload_date")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["album_list"] = Album.objects.order_by("name")

        return data


class AlbumView(ListView):
    template_name = "gallery/albums.html"
    model = Album
    pagenate_by = 50


class AlbumDetailView(DetailView):
    template_name = "gallery/album_detail.html"
    model = Album

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["image_list"] = Image.objects.filter(album=self.object).order_by("-upload_date")

        return data

gallery/templates/gallery/album_detail.html
{% extends "gallery/base.html" %}

{% block gallery_content %}

<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            {{album.name}} Album
        </h1>
    </div>
</header>
<main>
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">

        <div class="pb-10">
            <div class="flex flex-col items-center">
                <img class="h-20 w-20 object-cover rounded-full ring-2 ring-white" src="{{album.cover.url}}" />
            </div>
        </div>

        {% include "gallery/image_grid_component.html" %}
    </div>
</main>

{% endblock gallery_content %}

gallery/templates/gallery/albums.html
{% extends "gallery/base.html" %}

{% block gallery_content %}

<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            Albums
        </h1>
    </div>
</header>
<main>
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">

        <div>
            <div class="grid grid-cols-5">
                {% for album in album_list %}
                <div class="flex flex-col items-center">
                    <a href="{{album.get_absolute_url}}" class="border-2 border-transparent hover:border-white rounded-full">
                        <img class="h-20 w-20 object-cover rounded-full ring-2 ring-white" src="{{album.cover.url}}" />
                    </a>
                    <h1 class="py-1.5">
                        {{album.name}}
                    </h1>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</main>

{% endblock gallery_content %}

gallery/templates/gallery/base.html
{% extends "core/core.html" %}

{% block content %}

{% include "core/navbar.html" %}

<section class="">
    {% block gallery_content %}
    {% endblock gallery_content %}
</section>

{% include "core/footer.html" %}

{% endblock content %}

gallery/templates/gallery/image_grid_component.html
<div class="grid grid-cols-3 gap-4">
    {% for image in image_list %}
    <div class="flex flex-col gap-2">
        <a href="{{image.image.url}}" class="">
            <img src="{{image.image.url}}" class="" />
        </a>
    </div>

    {% endfor %}
</div>

gallery/templates/gallery/index.html
{% extends "gallery/base.html" %}

{% block gallery_content %}
<header class="bg-gray-50 text-black">
    <div class="mx-auto max-w-7xl px-4 py-16">
        <h1 class="text-5xl font-bold mb-5">
            Gallery
        </h1>
        <p class="">
            A collection of images that videos that I share.
        </p>
    </div>
</header>
<main>
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="flex flex-col gap-10">
            <div>
                <div class="flex gap-10 justify-center items-center">
                    {% for album in album_list %}
                    <div class="flex flex-col items-center">
                        <a href="{{album.get_absolute_url}}" class="border-2 border-transparent hover:border-white rounded-full">
                            <img class="h-20 w-20 object-cover rounded-full ring-2 ring-white" src="{{album.cover.url}}" />
                        </a>
                        <h1 class="py-1.5">
                            {{album.name}}
                        </h1>
                    </div>
                    {% endfor %}
                </div>
                <a href="{% url 'gallery:albums' %}" class="bg-green-300 text-gray-800 rounded-sm px-2 py-1.5 float-right">
                    View all
                </a>
            </div>

            <div class="w-full border border-gray-400"></div>

            {% include "gallery/image_grid_component.html" %}
        </div>
    </div>
</main>
{% endblock gallery_content %}