blog/urls.py
from django.urls import path, include

from . import views

from .feeds import BlogPostFeed

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/<slug:slug>/", views.PostView.as_view(), name="post"),
    path("tag/<int:pk>/", views.TagDetailView.as_view(), name="tag"),
    path("rss/", BlogPostFeed(), name="rss")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    #path("gallery/", include("gallery.urls", namespace="gallery")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from django.utils.text import slugify

from django_prose_editor.fields import ProseEditorField
from colorfield.fields import ColorField

from core.models import User

class Tag(models.Model):
    name = models.CharField(_("tag"), max_length=20)
    color = ColorField(default="#ff0000")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:tag", args=[self.id])


class Post(models.Model):
    title = models.CharField(_("title"), max_length=100)
    slug = models.SlugField(unique=True)
    description = models.CharField(_("description"), max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(_("created date"), auto_now_add=timezone.now)
    updated_date = models.DateTimeField(_("updated date"), auto_now=timezone.now)
    tags = models.ManyToManyField(Tag, blank=False, related_name="posts")
    body = ProseEditorField(_("body"), max_length=2000, blank=True)
    comments_allows = models.BooleanField(_("comments allowed"), default=True)
    view_count = models.IntegerField(default=0)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:post", args=[self.slug])


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_date = models.DateTimeField(_("created date"), auto_now_add=timezone.now)
    updated_date = models.DateTimeField(_("updated date"), auto_now=timezone.now)
    comment = models.TextField(_("comment"), max_length=500)

    def __str__(self):
        return f"{self.user} on '{self.post}'"

blog/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False)

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.contrib.syndication.views import Feed
from django.db.models import Q

from .models import Post, Tag

from .forms import SearchForm

class IndexView(ListView):
    template_name = "blog/index.html"
    allow_empty = True
    paginate_by = 20

    def get_queryset(self):
        query = self.request.GET.get("s")
        if query == None:
            query = ""

        return Post.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query),
            published=True).order_by("-created_date")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["tag_list"] = Tag.objects.order_by("name")
        data["form"] = SearchForm()


        return data


class PostView(DetailView):
    template_name = "blog/post.html"
    model = Post

    def get_object(self):
        obj = super().get_object()
        obj.view_count += 1
        obj.save()
        return obj

class TagDetailView(DetailView):
    template_name = "blog/tag_posts.html"
    model = Tag

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["post_list"] = Post.objects.filter(tags=self.object, published=True).order_by("-created_date")

        return data


class PostFeed(Feed):
    title = "Blog posts"
    description_template = "blog/index.html"

    def get_object(self, request, post_id):
        return Post.objects.get(pk=post_id)

    def link(self, obj):
        return obj.get_absolute_url()

    def items(self):
        return Post.objects.all()

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.description

blog/templates/blog/base.html
{% extends "core/core.html" %}

{% block content %}

{% include "core/navbar.html" %}

<section class="">
    {% block blog_content %}
    {% endblock blog_content %}
</section>

{% include "core/footer.html" %}

{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block blog_content %}

<header class="bg-gray-50 text-black">
  <div class="mx-auto max-w-7xl py-16">
    <h1 class="text-5xl font-bold mb-5">
      Blog
    </h1>
    <p class="">
      Collection of blog posts in which I discuss a wide range of topics from
      technology to my experiences.
    </p>
  </div>
</header>
<main>
  <div class="mx-auto max-w-7xl py-16">

    <div class="flex justify-between items-end">
      <div class="font-bold">
        {{post_list|length}} Result{{post_list|length|pluralize}}
      </div>

      {% comment %}
      <div class="flex">
        <form action="{% url 'blog:index' %}" method="get" class="flex items-center justify-center">
          {% csrf_token %}
          {{ form }}
          <input type="submit" value="Submit" class="bg-green-200 px-2 py-1.5 hover:cursor-pointer">
        </form>
      </div>

      <div class="">
        <i class="fa-solid fa-rss mx-1"></i>
        <a href="{% url 'blog:rss' %}" class="hover:underline text-blue-500 active:text-orange-500 visited:text-purple-500">

          Subscribe to RSS feed
        </a>
      </div>
      {% endcomment %}
    </div>

    <hr class="border border-black my-5">

    <div class="flex gap-10">
      <div class="flex-1 flex flex-col gap-y-2">
        {% include "blog/post_list.html" %}
      </div>
    </div>

    {% if is_paginated %}
    <div class="flex justify-center">
      <nav class="flex rounded hover:ring-1 hover:ring-inset hover:ring-gray-300 hover:bg-gray-50 active:bg-gray-200 active:shadow-inner">
        <ul class="flex">
          {% if page_obj.has_previous %}
          <li>
            <a href="?page=1" class="py-2 px-4 bg-white hover:bg-gray-100 text-gray-800 hover:text-gray-900">
              First
            </a>
          </li>
          <li>
            <a href="?page={{ page_obj.previous_page_number }}" class="py-2 px-4 bg-white hover:bg-gray-100 text-gray-800 hover:text-gray-900">
              Previous
            </a>
          </li>
          {% else %}
          <li>
            <a href="#" class="py-2 px-4 bg-white text-gray-400">
              First
            </a>
          </li>
          <li>
            <a href="#" class="py-2 px-4 bg-white text-gray-400">
              Previous
            </a>
          </li>
          {% endif %}


          <!-- Page Numbers -->
          {% for pg in page_obj.paginator.page_range %}
          {% if page_obj.number == pg %}
          <li>
            <a href="?page={{pg}}" class="py-2 px-4 bg-gray-100 rounded text-gray-800 hover:text-gray-900">
              {{pg}}
            </a>
          </li>
          {% else %}
          <li>
            <a href="?page={{pg}}" class="py-2 px-4 bg-white hover:bg-gray-100 text-gray-800 hover:text-gray-900">
              {{pg}}
            </a>
          </li>
          {% endif %}
          {% endfor %}

          <!-- Next Button -->

          {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}" class="py-2 px-4 bg-white hover:bg-gray-100 text-gray-800 hover:text-gray-900">
              Next
            </a>
          </li>
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="py-2 px-4 bg-white hover:bg-gray-100 text-gray-800 hover:text-gray-900">
              Last
            </a>
          </li>
          {% else %}
          <li>
            <a href="#" class="py-2 px-4 bg-white text-gray-400">
              Next
            </a>
          </li>
          <li>
            <a href="#" class="py-2 px-4 bg-white text-gray-400">
              Last
            </a>
          </li>
          {% endif %}

        </ul>
      </nav>
    </div>
    {% endif %}
  </div>
</main>

{% endblock blog_content %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}

{% block blog_content %}

<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <div class="">
      <h1 class="text-4xl font-bold tracking-tight text-gray-900 pb-2 text-center">
        {{post.title|capfirst}}
      </h1>
      <div class="flex flex-col text-xs text-gray-400">
        <div>Posted on: {{post.created_date|date:"D, d M Y"}}</div>
        <div>Last updated: {{post.updated_date|date:"D d, M Y"}}</div>

        <div class="flex gap-2 my-2">
          {% for tag in post.tags.all %}
          <a href="{{tag.get_absolute_url}}" class="bg-blue-200 hover:bg-blue-400 text-gray-600 hover:text-white text-xs px-1.5 py-0.5">
            {{tag.name}}
          </a>
          {% endfor %}
        </div>
      </div>
      <p class="my-2">
        {{post.description}}
      </p>
    </div>

    <hr class="border border-black my-10">

    <p class="">
      {{post.body|safe}}
    </p>


    {% with view_count=post.view_count %}
    <div class="text-sm my-5">
      Post has {{view_count}} view{{ view_count|pluralize }}
    </div>
    {% endwith %}
  </div>
</main>

{% endblock blog_content %}

blog/templates/blog/post_list.html
<div class="flex flex-col divide-y divide-solid gap-5">
  {% for post in post_list %}
  <div class="flex">
    <div class="flex-1">
      <div class="mb-4">
        <a href="{{post.get_absolute_url}}" class="text-blue-500 text-lg font-bold hover:underline">
          {{post.title}}
        </a>
        <p>
          {{post.description}}
        </p>
      </div>
      <div class="text-sm text-gray-500">{{post.created_date|date:"D d, M Y"}}</div>
    </div>
    <div class="">
      {% for tag in post.tags.all %}
      <a href="{{tag.get_absolute_url}}" class="bg-blue-200 hover:bg-blue-400 text-gray-600 hover:text-white text-xs px-1.5 py-px">
        {{tag.name}}
      </a>
      {% endfor %}
    </div>
  </div>

  {% empty %}

  <h1>There are no blog posts</h1>

  {% endfor %}
</div>

blog/templates/blog/tag_posts.html
{% extends "blog/base.html" %}

{% block blog_content %}

<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            Blog posts for {{tag.name}} tag
        </h1>
    </div>
</header>
<main>
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">

        <div class="flex mb-10">
            <input placeholder="Search..." class="px-1.5 py-1 border border-gray-400 rounded w-1/2" />
        </div>

        {% include "blog/post_list.html" %}

    </div>
</main>

{% endblock blog_content %}