blog/urls.py
from django.urls import path, include

from . import views

from .feeds import BlogPostFeed

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/<slug:slug>/", views.PostView.as_view(), name="post"),
    path("tag/<int:pk>/", views.TagDetailView.as_view(), name="tag"),
    path("rss/", BlogPostFeed(), name="rss")
]

core/urls.py
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap

from . import views

from blog.models import Post

info_dict = {
    "queryset": Post.objects.all(),
    "date_field": "updated_date",
}

app_name = "core"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),

    path("profile/logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/password_change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("profile/password_change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path("profile/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("profile/password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("profile/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("profile/reset/done/", views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("profile/", views.ProfileView.as_view(), name="profile"),

    path("sitemap.xml", sitemap, {"sitemaps" : { "blog_posts": GenericSitemap(info_dict) }}, name="sitemap")
]

gallery/urls.py
from django.urls import path, include

from . import views

app_name = "gallery"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("albums/", views.AlbumView.as_view(), name="albums"),
    path("albums/<int:pk>", views.AlbumDetailView.as_view(), name="album_detail")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    #path("gallery/", include("gallery.urls", namespace="gallery")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path, include

from . import views

app_name = "portfolio"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("cv/", views.CVView.as_view(), name="cv"),
    path("<slug:slug>/", views.ProjectDetailView.as_view(), name="project_detail"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class User(AbstractUser):
    image = models.ImageField(_('image'), upload_to="images/", default="images/default_image.jpg")

class Social(models.Model):
    name = models.CharField(max_length=20)
    website = models.URLField(max_length=100, blank=False)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User

class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        #fields = UserCreationForm.Meta.fields + ("image",)
        fields = ["username", "password1"]

class LoginForm(AuthenticationForm):
    pass

# class ChangeUserForm(models.Forms):
#     fields = ["username", "image"]


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    body = forms.CharField(widget=forms.Textarea, max_length=2000)

    def send_email(self):
        # @TODO: Only send email a valid email has been set from within
        # settings.py.
        print("Sending contact form")

core/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.views.generic.edit import FormView

from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Social
from .forms import ContactForm, SignUpForm, LoginForm

from blog.models import Post

class IndexView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["social_list"] = Social.objects.order_by("name")
        data["post_list"] = Post.objects.filter(published=True).order_by("-created_date")[:5]

        return data


class ContactView(FormView):
    template_name = "core/contact.html"
    form_class = ContactForm
    success_url = "/thanks/"

    def form_valid(self, form):
        form.send_email()

        return super().form_valid(form)


# @TODO: Redirect if already signed in
class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("login")
    template_name = "core/signup.html"

class LoginView(auth_views.LoginView):
    template_name = "core/login.html"
    authentication_form = LoginForm
    next_page = "/"
    redirect_authenticated_user = True

class LogoutView(auth_views.LogoutView):
    template_name = "core/logout.html"
    next_page = "/"

class PasswordChangeView(auth_views.PasswordChangeView):
    #template_name = "core/password_change_form.html"
    pass

class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    #template_name = "core/password_change_done.html"
    pass

class PasswordResetView(auth_views.PasswordResetView):
    #template_name = "core/password_reset_form.html"
    pass

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    #template_name = "core/password_reset_done.html"
    pass

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    #template_name = "core/password_reset_confirm.html"
    pass

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    #template_name = "core/password_reset_complete.html"
    pass

class ProfileView(LoginRequiredMixin, TemplateView):
    login_url = "/login"
    redirect_field_name = "redirect_to"
    template_name = "core/profile.html"

core/templates/core/base.html
{% extends "core/core.html" %}

{% block content %}

{% include "core/navbar.html" %}

<section class="">
    {% block core_content %}
    {% endblock core_content %}
</section>

{% include "core/footer.html" %}

{% endblock content %}

core/templates/core/contact.html
<form action="{% url 'core:index' %}" method="post" class="flex items-center justify-center">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" class="">
</form>

core/templates/core/core.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-Y0Q73276KJ"></script>
        <script>
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments);}
         gtag('js', new Date());

         gtag('config', 'G-Y0Q73276KJ');
        </script>


        <title>Zakariya Oulhadj</title>

        {% load static %}

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'core/styles.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'core/favicon.ico' %}">

        <script src="https://unpkg.com/htmx.org@1.9.11"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://kit.fontawesome.com/5ccda46141.js" crossorigin="anonymous"></script>

    </head>

    <body class="">
        {% block content %}
        {% endblock content %}
    </body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% load static %}
{% block core_content %}

<main>
  <div class="mx-auto max-w-7xl py-6">
    <div class="flex gap-4 mb-10">
      <div class="">
        <img src="{% static 'core/images/me.jpg' %}" class="border border-gray-400 mb-2" width="200" />
        <figcaption class="text-center italic text-xs w-[200px] text-gray-600">
          "Hardware is only as good as the software that drives it"
        </figcaption>
      </div>
      <div>
        <h1 class="font-bold text-xl">
          BSc. Zakariya Oulhadj
        </h1>
        <h1 class="bold">
          Graduate Software Engineer
        </h1>
        <h1 class="">
          London, UK
        </h1>
        <div>
          <a href="mailto:contact@zakariyaoulhadj.com" class="hover:underline text-blue-500 active:text-orange-500 visited:text-purple-500">
            contact@zakariyaoulhadj.com
          </a>
        </div>

      </div>
    </div>

    {% if post_list %}
    <div class="">
      <h1 class="font-bold text-2xl">
        Recent posts
      </h1>
      <ul class="mb-5">
        {% for post in post_list %}
        <li class="flex items-center gap-2">
          <div class="text-sm text-gray-500">
            {{post.created_date|date:"d/m/Y"}}
          </div>
          <span class="text-gray-500">
            &mdash;
          </span>
          <a href="{{post.get_absolute_url}}" class="text-blue-500 hover:underline active:text-orange-500 visited:text-purple-500">
            {{post.title}}
          </a>
        </li>
        {% endfor %}
      </ul>
      <p>
        View all my blog posts
        <a href="{% url 'blog:index' %}" class="text-blue-500 hover:underline active:text-orange-500 visited:text-purple-500">
          here
        </a>
      </p>
    </div>
    {% endif %}
  </div>
</main>

{% endblock core_content %}

core/templates/core/login.html
{% extends "core/base.html" %}


{% block content %}

{% include "core/navbar.html" %}
<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            Login
        </h1>
    </div>
</header>

    <main>
        <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
            {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %}

            {% if next %}
            {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
            {% else %}
            <p>Please login to see this page.</p>
            {% endif %}
            {% endif %}

            <form method="post" action="{% url 'core:login' %}">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>{{ form.username.label_tag }}</td>
                        <td>{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password.label_tag }}</td>
                        <td>{{ form.password }}</td>
                    </tr>
                </table>

                <button type="submit" class="inline-flex justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 active:bg-gray-200 active:shadow-inner">
                    Login
                </button>
                <input type="hidden" name="next" value="{{ next }}">
            </form>

            {# Assumes you set up the password_reset view in your URLconf #}
            <a href="{% url 'core:password_reset' %}" class="hover:underline text-blue-500">
                Lost password?
            </a>
        </div>
    </main>



{% endblock %}

core/templates/core/logout.html
{% extends "core/base.html" %}

{% block content %}
<h1>This is the logout page</h1>
{% endblock %}

core/templates/core/navbar.html
<div class="border-b border-stone-100">
    <div class="mx-auto max-w-7xl">
        <div class="flex justify-center items-center gap-5 py-1">
            <a href="{% url 'core:index' %}" class="text-blue-500 hover:underline active:text-orange-500 visited:text-purple-500">
                Home
            </a>
            <a href="{% url 'blog:index' %}" class="text-blue-500 hover:underline active:text-orange-500 visited:text-purple-500">
                Blog
            </a>
            <a href="{% url 'portfolio:index' %}" class="text-blue-500 hover:underline active:text-orange-500 visited:text-purple-500">
                Portfolio
            </a>
            <a href="{% url 'portfolio:cv' %}" class="text-blue-500 hover:underline active:text-orange-500 visited:text-purple-500">
                CV
            </a>
            {% comment %}
            <a href="{% url 'gallery:index' %}" class="text-blue-500 hover:underline active:text-orange-500 visited:text-purple-500">
                Gallery
            </a>
            {% endcomment %}
        </div>
    </div>
</div>

core/templates/core/password_change_done.html
{% extends "core/base.html" %}

{% block content %}
<h1>This is the password change done page</h1>
{% endblock %}

core/templates/core/password_change_form.html
{% extends "core/base.html" %}

{% block content %}
<h1>This is the password change form page</h1>
{% endblock %}

core/templates/core/password_reset_complete.html
{% extends "core/base.html" %}

{% block content %}
<h1>This is the password reset complete page</h1>
{% endblock %}

core/templates/core/password_reset_done.html
{% extends "core/base.html" %}

{% block content %}
<h1>This is the password reset done page</h1>
{% endblock %}

core/templates/core/password_reset_form.html
{% extends "core/base.html" %}

{% block content %}
<h1>This is the password reset form page</h1>
{% endblock %}

core/templates/core/profile.html
{% extends "core/base.html" %}

{% block content %}

{% include "core/navbar.html" %}

<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            Profile
        </h1>
    </div>
</header>
<main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
        <a href="">
            <img class="inline-block h-20 w-20 rounded-full ring-2 ring-white hover:ring-stone-200" src="{{user.image.url}}" alt="">
        </a>

        <div class="">
            <div class="font-bold">Username</div> {{ user.username }}
        </div>
        <div class="flex gap-2">
            <a href="{% url 'core:password_change' %}" class="flex-none rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">
                Change password
            </a>
            <a href="#" class="flex-none rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">
                Delete account
            </a>
        </div>
    </div>
</main>
{% endblock content %}

core/templates/core/signup.html
{% extends "core/base.html" %}


{% block content %}

{% include "core/navbar.html" %}

<header class="bg-white">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold tracking-tight text-gray-900">
            Sign Up
        </h1>
    </div>
</header>

<main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="inline-flex justify-center gap-x-1.5 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 active:bg-gray-200 active:shadow-inner">
                Sign Up
            </button>
        </form>
    </div>
</main>

{% endblock %}